---
abstract: 'We are Austrian CPAN authors'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
  - 'Philipp Gortan <gortan@gmail.com>'
build_requires:
  Acme::CPANAuthors: 0
  Carp: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::Differences: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-Austrian
provides:
  Acme::CPANAuthors::Austrian:
    file: lib/Acme/CPANAuthors/Austrian.pm
    version: 1.131810
requires:
  Acme::CPANAuthors::Register: 0
  perl: 5.008
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Acme-CPANAuthors-Austrian
  homepage: http://search.cpan.org/dist/Acme-CPANAuthors-Austrian/
  repository: git://github.com/mephinet/Acme-CPANAuthors-Austrian.git
version: 1.131810
